-- KnowU hackathon analytics setup
-- Run as a role allowed to create the database/schema/table, then grant the
-- runtime role INSERT and SELECT privileges according to your account policy.

CREATE DATABASE IF NOT EXISTS KNOWU;
CREATE SCHEMA IF NOT EXISTS KNOWU.ANALYTICS;

USE DATABASE KNOWU;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS INFERENCE_RUNS (
  ID VARCHAR NOT NULL,
  TIMESTAMP TIMESTAMP_TZ NOT NULL,
  MODEL VARCHAR NOT NULL,
  BASELINE_INPUT_TOKENS NUMBER NOT NULL,
  OPTIMIZED_INPUT_TOKENS NUMBER NOT NULL,
  TOKENS_SAVED NUMBER NOT NULL,
  REDUCTION_PERCENT FLOAT NOT NULL,
  ACTUAL_INPUT_TOKENS NUMBER,
  OUTPUT_TOKENS NUMBER,
  CONTEXT_BUDGET_TOKENS NUMBER NOT NULL DEFAULT 0,
  CONTEXT_ESTIMATED_TOKENS NUMBER NOT NULL DEFAULT 0,
  CONTEXT_UNITS_CONSIDERED NUMBER NOT NULL DEFAULT 0,
  CONTEXT_UNITS_SENT NUMBER NOT NULL DEFAULT 0,
  CONTEXT_UNITS_OMITTED NUMBER NOT NULL DEFAULT 0,
  CONTEXT_DETAIL_LEVEL VARCHAR NOT NULL DEFAULT 'legacy',
  PROVIDER_PREFLIGHT_INPUT_TOKENS NUMBER,
  CACHE_READ_INPUT_TOKENS NUMBER,
  CACHE_WRITE_INPUT_TOKENS NUMBER,
  LATENCY_MS NUMBER NOT NULL,
  ESTIMATED_COST_USD FLOAT,
  MEMORY_COUNT NUMBER NOT NULL,
  MODE VARCHAR NOT NULL,
  MEMORY_PROVIDER VARCHAR NOT NULL,
  MEASUREMENT_METHOD VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT INFERENCE_RUNS_PK PRIMARY KEY (ID)
);

-- Keep reruns safe when upgrading a table created by an earlier KnowU build.
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_BUDGET_TOKENS NUMBER NOT NULL DEFAULT 0;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_ESTIMATED_TOKENS NUMBER NOT NULL DEFAULT 0;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_UNITS_CONSIDERED NUMBER NOT NULL DEFAULT 0;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_UNITS_SENT NUMBER NOT NULL DEFAULT 0;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_UNITS_OMITTED NUMBER NOT NULL DEFAULT 0;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CONTEXT_DETAIL_LEVEL VARCHAR NOT NULL DEFAULT 'legacy';
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS PROVIDER_PREFLIGHT_INPUT_TOKENS NUMBER;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CACHE_READ_INPUT_TOKENS NUMBER;
ALTER TABLE INFERENCE_RUNS ADD COLUMN IF NOT EXISTS CACHE_WRITE_INPUT_TOKENS NUMBER;

CREATE OR REPLACE VIEW CONTEXT_ECONOMICS_SUMMARY AS
SELECT
  DATE_TRUNC('day', TIMESTAMP) AS DAY,
  MODEL,
  MODE,
  CONTEXT_DETAIL_LEVEL,
  COUNT(*) AS RUNS,
  SUM(BASELINE_INPUT_TOKENS) AS BASELINE_INPUT_TOKENS,
  SUM(OPTIMIZED_INPUT_TOKENS) AS OPTIMIZED_INPUT_TOKENS,
  SUM(TOKENS_SAVED) AS TOKENS_SAVED,
  SUM(CONTEXT_BUDGET_TOKENS) AS CONTEXT_BUDGET_TOKENS,
  SUM(CONTEXT_ESTIMATED_TOKENS) AS CONTEXT_ESTIMATED_TOKENS,
  DIV0(SUM(CONTEXT_ESTIMATED_TOKENS), SUM(CONTEXT_BUDGET_TOKENS)) AS CONTEXT_BUDGET_UTILIZATION,
  SUM(CONTEXT_UNITS_CONSIDERED) AS CONTEXT_UNITS_CONSIDERED,
  SUM(CONTEXT_UNITS_SENT) AS CONTEXT_UNITS_SENT,
  SUM(CONTEXT_UNITS_OMITTED) AS CONTEXT_UNITS_OMITTED,
  DIV0(SUM(CONTEXT_UNITS_SENT), SUM(CONTEXT_UNITS_CONSIDERED)) AS CONTEXT_UNIT_INCLUSION_RATE,
  SUM(COALESCE(PROVIDER_PREFLIGHT_INPUT_TOKENS, 0)) AS PROVIDER_PREFLIGHT_INPUT_TOKENS,
  SUM(COALESCE(CACHE_READ_INPUT_TOKENS, 0)) AS CACHE_READ_INPUT_TOKENS,
  SUM(COALESCE(CACHE_WRITE_INPUT_TOKENS, 0)) AS CACHE_WRITE_INPUT_TOKENS,
  DIV0(
    SUM(COALESCE(CACHE_READ_INPUT_TOKENS, 0)),
    SUM(COALESCE(ACTUAL_INPUT_TOKENS, 0) + COALESCE(CACHE_READ_INPUT_TOKENS, 0) + COALESCE(CACHE_WRITE_INPUT_TOKENS, 0))
  ) AS CACHE_READ_SHARE,
  AVG(REDUCTION_PERCENT) AS AVG_REDUCTION_PERCENT,
  AVG(LATENCY_MS) AS AVG_LATENCY_MS,
  SUM(ESTIMATED_COST_USD) AS KNOWN_ESTIMATED_COST_USD,
  COUNT_IF(ESTIMATED_COST_USD IS NULL) AS MISSING_COST_RUNS,
  IFF(
    COUNT_IF(ESTIMATED_COST_USD IS NULL) = 0,
    SUM(ESTIMATED_COST_USD),
    NULL
  ) AS ESTIMATED_COST_USD
FROM INFERENCE_RUNS
GROUP BY 1, 2, 3, 4;

-- Example dashboard query
SELECT *
FROM CONTEXT_ECONOMICS_SUMMARY
ORDER BY DAY DESC, MODEL, MODE;
