-- KnowU hackathon analytics setup
-- Run as a role allowed to create the database/schema/table, then grant the
-- runtime role INSERT and SELECT privileges according to your account policy.

CREATE DATABASE IF NOT EXISTS KNOWU;
CREATE SCHEMA IF NOT EXISTS KNOWU.ANALYTICS;

USE DATABASE KNOWU;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS INFERENCE_RUNS (
  ID VARCHAR NOT NULL,
  TIMESTAMP TIMESTAMP_TZ NOT NULL,
  MODEL VARCHAR NOT NULL,
  BASELINE_INPUT_TOKENS NUMBER NOT NULL,
  OPTIMIZED_INPUT_TOKENS NUMBER NOT NULL,
  TOKENS_SAVED NUMBER NOT NULL,
  REDUCTION_PERCENT FLOAT NOT NULL,
  ACTUAL_INPUT_TOKENS NUMBER,
  OUTPUT_TOKENS NUMBER,
  LATENCY_MS NUMBER NOT NULL,
  ESTIMATED_COST_USD FLOAT,
  MEMORY_COUNT NUMBER NOT NULL,
  MODE VARCHAR NOT NULL,
  MEMORY_PROVIDER VARCHAR NOT NULL,
  MEASUREMENT_METHOD VARCHAR NOT NULL,
  INGESTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT INFERENCE_RUNS_PK PRIMARY KEY (ID)
);

CREATE OR REPLACE VIEW CONTEXT_ECONOMICS_SUMMARY AS
SELECT
  DATE_TRUNC('day', TIMESTAMP) AS DAY,
  MODEL,
  MODE,
  COUNT(*) AS RUNS,
  SUM(BASELINE_INPUT_TOKENS) AS BASELINE_INPUT_TOKENS,
  SUM(OPTIMIZED_INPUT_TOKENS) AS OPTIMIZED_INPUT_TOKENS,
  SUM(TOKENS_SAVED) AS TOKENS_SAVED,
  AVG(REDUCTION_PERCENT) AS AVG_REDUCTION_PERCENT,
  AVG(LATENCY_MS) AS AVG_LATENCY_MS,
  SUM(COALESCE(ESTIMATED_COST_USD, 0)) AS ESTIMATED_COST_USD
FROM INFERENCE_RUNS
GROUP BY 1, 2, 3;

-- Example dashboard query
SELECT *
FROM CONTEXT_ECONOMICS_SUMMARY
ORDER BY DAY DESC, MODEL, MODE;
